### PR TITLE
small resizing on Main Menu to fix iPhone issue

### PR DESCRIPTION
**Pull request by shanefirnekas**

### CODE REVIEW

**Comment by stanley-dejesus** [comment]
@adetoito74 Can you test to see if the buttons are fixed on your iPhone?

**Comment by stanley-dejesus** [comment]
@shanefirnekas Can you wrap the body widget with SingleChildScrollView? It will enable scrolling if the keyboard ever pops up. See the Screenshot and use it as an example. Also, pull the developer branch into your branch once @adetoito74 confirms the issue has been fixed.  Thanks!

image

**Review by mambaExpress74 — APPROVED** [review]

**Comment by mambaExpress74** [comment]
> @adetoito74 Can you test to see if the buttons are fixed on your iPhone?

@shanefirnekas @stanley-dejesus Yes, the buttons are displaying properly on my iPhone.

**Comment by mambaExpress74** [comment]
> > @adetoito74 Can you test to see if the buttons are fixed on your iPhone?
> 
> @shanefirnekas @stanley-dejesus Yes, the buttons are displaying properly on my iPhone.

**Pull request closed without merging**
