### PR TITLE
Speech to text

### PR DESCRIPTION
**Pull request by ccolbert15**

### CODE REVIEW

**Review by rsamps15 — APPROVED** [review]

**Review by zsloan112 — APPROVED** [review]
Still having build issues on my machine, but the Android Pipeline is passing, so it it likely a set up with my android simulator

**Comment by zsloan112** [comment]
@ccolbert15 Looks like there is a merge conflict, do you want me to resolve?

**Comment by ccolbert15** [comment]
> @ccolbert15 Looks like there is a merge conflict, do you want me to resolve?

@zsloan112 I just resolved them, but I am seeing one error in main_menu.dart on the line "await getEmails();", saying that it expected an argument. What does it expect for that specific situation?

**Comment by zsloan112** [comment]
> > @ccolbert15 Looks like there is a merge conflict, do you want me to resolve?
> 
> @zsloan112 I just resolved them, but I am seeing one error in main_menu.dart on the line "await getEmails();", saying that it expected an argument. What does it expect for that specific situation?

It is expecting a `[DateTime? pickedDate]` so I believe adding `picked` should solve this, since that is the variable the date is stored in when the user selects it from the date picker.

**Comment by ccolbert15** [comment]
> > > @ccolbert15 Looks like there is a merge conflict, do you want me to resolve?
> > 
> > 
> > @zsloan112 I just resolved them, but I am seeing one error in main_menu.dart on the line "await getEmails();", saying that it expected an argument. What does it expect for that specific situation?
> 
> It is expecting a `[DateTime? pickedDate]` so I believe adding `picked` should solve this, since that is the variable the date is stored in when the user selects it from the date picker.

That doesn't seem to do the trick, says `picked` is an undefined name

**Comment by ccolbert15** [comment]
> > > > @ccolbert15 Looks like there is a merge conflict, do you want me to resolve?
> > > 
> > > 
> > > @zsloan112 I just resolved them, but I am seeing one error in main_menu.dart on the line "await getEmails();", saying that it expected an argument. What does it expect for that specific situation?
> > 
> > 
> > It is expecting a `[DateTime? pickedDate]` so I believe adding `picked` should solve this, since that is the variable the date is stored in when the user selects it from the date picker.
> 
> That doesn't seem to do the trick, says `picked` is an undefined name

Should probably get your pull request pulled in first and then see if it fixes it on this branch

**Pull request merged**
