### PR TITLE
Feature/minor UI updates

### PR DESCRIPTION
**Pull request by zsloan112**
Updating UI look some to add app bar and make it consistent between pages, also fixes bottom bar not displaying on all pages.
Adds in some hook for STT and TTS.

### CODE REVIEW

**Comment by ccolbert15** [comment]
On line 386 of main_menu.dart I am seeing the error "The argument type 'DateTime' can't be assigned to the parameter type 'String'"

**Comment by zsloan112** [comment]
> On line 386 of main_menu.dart I am seeing the error "The argument type 'DateTime' can't be assigned to the parameter type 'String'"

Rats, seeing on my end as well. I will investigate.

**Comment by zsloan112** [comment]
@ccolbert15 This branch should be good now. Once we get this merged in to developer then we can get your branch up to date with developer.

**Review by ccolbert15 — APPROVED** [review]

**Review by rsamps15 — APPROVED** [review]
looks good to me

**Pull request merged**
