### PR TITLE
Feature/team b UI implementation

### PR DESCRIPTION
**Pull request by zsloan112**
Initial implementation of the UI components. Will likely need to be adjusted as things are integrated.

Gets both teams set up to start integrating things much easier.

### CODE REVIEW

**Comment by ccolbert15** [comment]
I just ran your code and I'm not sure if the main menu is exactly as expected. I see buttons to chose a Daily Digest or emails for a specific date, but I don't see anything to read the unread Daily Digests or emails.

**Comment by zsloan112** [comment]
> I just ran your code and I'm not sure if the main menu is exactly as expected. I see buttons to chose a Daily Digest or emails for a specific date, but I don't see anything to read the unread Daily Digests or emails. 

I should have those updates in there later this afternoon. I put the PR up so people could start looking through it since it's a decent amount of changes. You are on Mac correct?

**Comment by ccolbert15** [comment]
> I should have those updates in there later this afternoon. I put the PR up so people could start looking through it since it's a decent amount of changes. You are on Mac correct?

Ok sounds good! Yes I am

**Comment by zsloan112** [comment]
> > I should have those updates in there later this afternoon. I put the PR up so people could start looking through it since it's a decent amount of changes. You are on Mac correct?
> 
> 
> 
> Ok sounds good! Yes I am

Does the formatting look ok on iPhone? I'm unable to run and iPhone emulator on windows

**Comment by ccolbert15** [comment]
> > > I should have those updates in there later this afternoon. I put the PR up so people could start looking through it since it's a decent amount of changes. You are on Mac correct?
> > 
> > 
> > Ok sounds good! Yes I am
> 
> Does the formatting look ok on iPhone? I'm unable to run and iPhone emulator on windows

Yes the formatting looks good, I ran it on iPhone 11

**Review by bandrews20 — APPROVED** [review]

**Review by rsamps15 — APPROVED** [review]

**Pull request merged**
