### PR TITLE
Fix date speech commands and delete unused files.

### PR DESCRIPTION
**Pull request by ccolbert15**

### CODE REVIEW

**Review by ItsDang — APPROVED** [review]

**Review by sarahathomas — APPROVED** [review]
Working for me.

**Review by Bgartr2 — APPROVED** [review]

**Comment by stanley-dejesus** [comment]
Why is the CI/CD off?

**Comment by zsloan112** [comment]
> Why is the CI/CD off?

The pipeline didn't run for this pull request?

**Comment by stanley-dejesus** [comment]
> > Why is the CI/CD off?
> 
> The pipeline didn't run for this pull request?

I don't think so. It might be because of the conflict. @ccolbert15, can you look into the conflict?

**Comment by zsloan112** [comment]
That is likely it. I believe that the pipeline does not run when there are conflicts since it will not compile

> > > Why is the CI/CD off?
> 
> > 
> 
> > The pipeline didn't run for this pull request?
> 
> 
> 
> I don't think so. It might be because of the conflict. @ccolbert15, can you look into the conflict?

**Pull request merged**
